name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
            MODEL_NAME=${{ secrets.MODEL_NAME }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/digitaltwin-tg-bot:${{ steps.date.outputs.date }}
